### ISSUE TITLE
Dairy MPP Tool Page Not Rendering

### ISSUE THREAD

**Issue by usdafsajeff** [usdafsajeff/fsasoftlaunch#1]
![mppcapture](https://cloud.githubusercontent.com/assets/11912696/7107314/ca94728c-e12f-11e4-9062-e8af6604fec3.JPG)
Top half of http://www.fsa.usda.gov/FSA/pages/content/farmBill/fb_MPPDTool.jsp does render on work IE9 browser.

**Comment by M16George** [comment]
HTML and javascript errors: HTML1114: Codepage iso-8859-1 from (HTTP header) overrides conflicting codepage utf-8 from (META tag) 
fb_MPPDTool.jsp
SCRIPT5009: 'jQuery' is undefined 
fb_MPPDTool.jsp, line 328 character 3

**Comment by M16George** [comment]
All Errors:

http://www.fsa.usda.gov/FSA/fsa_resources/foundation/css/normalize.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/foundation/js/vendor/custom.modernizr.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/custom/css/fsa_custom_styles.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/custom/css/tab_styles.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/custom/css/nav_styles.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/foundation/js/foundation.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/foundation/js/vendor/jquery.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/images/usda-green-logo77.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/errorapp?area=error&subject=landing&topic=landing Failed to load resource: the server responded with a status of 404 (Not Found)
fb_MPPDTool.jsp:328 Uncaught ReferenceError: jQuery is not defined
http://www.fsa.usda.gov/FSA/fsa_resources/images/socialicons/sc-fcebook-large.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/images/usda-green-logo77.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/images/socialicons/sc-GD-large.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/images/socialicons/sc-twitter-large.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/images/socialicons/sc-rss-large.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/images/socialicons/sc-youtube-large.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/custom/css/tab_styles.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/foundation/css/foundation.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/custom/css/nav_styles.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/custom/css/fsa_custom_styles.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.fsa.usda.gov/FSA/fsa_resources/foundation/css/normalize.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by MartinLeborgne** [comment]
In progress (akamai) Assigned to Martin.  Pending Akamai push.

**Comment by MartinLeborgne** [comment]
Completed and fixed and verified in Akamai v 185.
Can be closed.

**Comment by M16George** [comment]
unable to access the tool from the fsa homepage Popular Topics menu. http://origin2.www.fsa.usda.gov/mpptool
Not Found

The requested URL /mpptool was not found on this server.

**Comment by MartinLeborgne** [comment]
Thats all correct....bec youre doing a shortcut in origin.
/mpptool works in www

This can all be closed

**Comment by M16George** [comment]
Yes, this url works from Popular Topics: http://www.fsa.usda.gov/FSA/pages/content/farmBill/fb_MPPDTool.jsp
