### ISSUE TITLE
Link going back to origin in Civil Rights section

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#11]
It looks like a bunch in Structure and Organiztion - Multiple links going back to origin: 

http://origin2.www.fsa.usda.gov/about-fsa/structure-and-organization/office-of-the-administrator/office-of-civil-rights/equal-employment-opportunity-program/eeo-counselor-list/index

This is in the Civil Rights section
Several examples listed below

**Comment by angelamathews** [comment]
Another one in that section: http://origin2.www.fsa.usda.gov/about-fsa/structure-and-organization/office-of-the-administrator/office-of-civil-rights/equal-employment-opportunity-program/employment-discrimination-complaints/index

**Comment by angelamathews** [comment]
http://origin2.www.fsa.usda.gov/about-fsa/structure-and-organization/office-of-the-administrator/office-of-civil-rights/minority-and-socially-disadvantaged-farmers-assistance/index

**Comment by angelamathews** [comment]
http://origin2.www.fsa.usda.gov/about-fsa/structure-and-organization/office-of-the-administrator/office-of-civil-rights/resources/index

**Comment by angelamathews** [comment]
http://origin2.www.fsa.usda.gov/about-fsa/structure-and-organization/office-of-the-administrator/office-of-civil-rights/civil-rights-offices/index

**Comment by angelamathews** [comment]
http://origin2.www.fsa.usda.gov/about-fsa/structure-and-organization/office-of-the-administrator/office-of-external-affairs/index 
Office of External Affairs

**Comment by usdafsajeff** [comment]
I believe this issue is resolved
