### ISSUE TITLE
DACO page not found; procurement solicitations

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#14]
http://www.fsa.usda.gov/programs-and-services/commodity-operations/commodity-operations-reports/www.fsa.usda.gov/FSA/dacoReports?area=home&subject=coop&topic=rpt-ps 

page not found

**Comment by usdafsajeff** [comment]
Which page is this link on?

**Comment by MartinLeborgne** [comment]
Resolved.
