### ISSUE TITLE
RSS Feeds for GovDelivery Receiving 404 Error

### ISSUE THREAD

**Issue by usdafsajeff** [usdafsajeff/fsasoftlaunch#16]
Pagewatch RSS feeds used in GovDelivery is not working as page is not found.

http://www.fsa.usda.gov/FSA/createRSS?newstype=daco&category=Market-Rates

Temporarily changed to http://origin.www.fsa.usda.gov/FSA/createRSS?newstype=daco&category=Market-Rates

Until the issue can be fixed for a couple of topics. Market Rates, Notices.

**Comment by MartinLeborgne** [comment]
In progress of being resolved (akamai push)

**Comment by MartinLeborgne** [comment]
Resolved and fixed in Akamai v

**Comment by MartinLeborgne** [comment]
Fixed in Akamai v 183
