### ISSUE TITLE
Navigation has to be provided

### ISSUE THREAD

**Issue by SubbuSarma** [usdafsajeff/fsasoftlaunch#20]
When User click on Newsroom  in menu   and browses other pages  like AboutFSA, it  is going to Origin instead of origin2.

Example: http://www.fsa.usda.gov/FSA/webapp?area=newsroom&subject=landing&topic=landing
User Click AboutFsa from Menu
Example:    http://www.fsa.usda.gov/FSA/webapp?area=about&subject=landing&topic=landing

It should go here.
http://www.fsa.usda.gov/FSA/webapp?area=about&subject=landing&topic=landing

**Comment by SubbuSarma** [comment]
Issue has been fixed

**Comment by NavyaVullanki** [comment]
I fixed the issue by redirecting the URLs of AboutFSA, ContactUS, Online Services, Help on the Nav bar of old page to Percussion New Pages. This change is made in the config files.
