### ISSUE TITLE
Link to Percussion

### ISSUE THREAD

**Issue by usdafsajeff** [usdafsajeff/fsasoftlaunch#23]
Need to add URL forward from http://www.fsa.usda.gov/percussion to the Percussion server as we designed. We should be challenged by eAuth at the URL. May need to coordinate with Vivek on this one.

**Comment by MartinLeborgne** [comment]
Main task: Implement E-Auth

**Comment by usdafsajeff** [comment]
Vivek fixed on 04-15-2015 all working.
