### ISSUE TITLE
In http://fsa.usda.gov/FSA/, not www.fsa.usda.gov,  every subject from Related Topics gives me a page not found

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#25]
When I am on http://fsa.usda.gov/FSA/, NOT www.fsa.usda.gov, every program I click on from the Related Topics section comes up page not found (tried repeatedly). Same with Popular Topics... Only the links on the Home page to DMPP, HRD, Fact Sheets and the individual News Releases are working.  Again, in IE 9, not IE 9 compat. view

**Comment by usdafsajeff** [comment]
As of 4/15/2015 still an issue.
