### ISSUE TITLE
Farm Bill/Energy/BCAP ends in a paragraph... where are the rest of BCAP's pages?

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#26]
www.fsa.usda.gov
Home
 / Programs and Services
 / Farm Bill Home
 / Energy 
/ Biomass Crop Assistance Program 

Where is the rest of BCAP? There is only a paragraph instead of several pages. Shouldn't this link to ALL of BCAP? IE 9 not IE 9 compat view

Home
 / Programs and Services
 / Energy Programs 
/ Biomass Crop Assistance Program works and goes to ALL BCAP pages.

**Comment by SubbuSarma** [comment]
we have replicated wat is there in old site  for Farmbill. you can check the url.

http://www.fsa.usda.gov/FSA/fbapp?area=home&subject=enrg&topic=bcap
