### ISSUE TITLE
APFO Ordering NAIP Imagery page: links going back to old site

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#29]
www.fsa.usda.gov in IE 9, not IE 9 compat view

Home
 / Programs and Services
 / Aerial Photography
 / Imagery Programs
 / NAIP Imagery
 / Ordering NAIP Imagery 

http://www.fsa.usda.gov/programs-and-services/aerial-photography/imagery-programs/naip-imagery/ordering-naip-imagery/index

NAIP, NAIP Product Sheet, and Catalog Listing links going back to old site.

**Comment by SubbuSarma** [comment]
I have fixed it and it is going to new site

**Comment by angelamathews** [comment]
Verified, NAIP, NAIP Product Sheet, and Catalog Listings now going to new site pages.
