### ISSUE TITLE
Interior Landing Page Masthead linking to old home page

### ISSUE THREAD

**Issue by usdafsajeff** [usdafsajeff/fsasoftlaunch#3]
The mast heads on the interior pages are linking to the old home link

![aerial photography](https://cloud.githubusercontent.com/assets/11912696/7107465/40ddf1e4-e134-11e4-89b7-a5d644291c27.png)

**Comment by NavyaVullanki** [comment]
Just fixed this issue. Now the FSA on the mast heads for interior pages will be pointing to new Percussion Home Page.

**Comment by usdafsajeff** [comment]
Per Navya issue resolved
