### ISSUE TITLE
APFO Status Maps: two links going to 'page not found'

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#30]
www.fsa.usda.gov in IE 9, not IE 9 compt view
Home
 / Programs and Services
 / Aerial Photography
 / Status Maps 

http://www.fsa.usda.gov/programs-and-services/aerial-photography/status-maps/index

Archived Status Maps 
Archived status maps are kept for the NAIP program only. To view these archived status maps, click here.

NAIP 2002-2014 Coverage Status Map
Use the Interactive NAIP 2002-2014 Coverage status map below for all NAIP years or Click here>> to view and download historical NAIP coverage maps

**Comment by sonjaeasley** [comment]
I have fixed the links and they are going to the new site.
