### ISSUE TITLE
DACO- Procurement and Sales page: WBSCM link goes to old site (we have new page for WBSCM))

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#34]
www.fsa.usda.gov in IE 9

http://www.fsa.usda.gov/programs-and-services/commodity-operations/procurement-and-sales/dairy/index

Under  Solicitation Informationf:
The web based supply chain management link is going to the old site, but we have a page for WBSCM in the new site. 

ARchived Dairy Price Support link goes to main Archived Bulk Commodites page but only to the top of the page,  not to the Dairy Price Support section.

**Comment by SubbuSarma** [comment]
I have fixed the url and it is going to new site

**Comment by usdafsajeff** [comment]
Fixed
