### ISSUE TITLE
http://www.apfo.usda.gov/FSA/ going to FSA home page and not straight to APFO

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#36]
http://www.apfo.usda.gov/FSA/ just goes to the FSA home page and not to APFO site. Checked in IE 9, not IE 9 compat view

**Comment by usdafsajeff** [comment]
APFO created http://www.apfo.usda.gov without our permission years ago and now since we moved the site its broken.

**Comment by MartinLeborgne** [comment]
ML: Closed out. Resolved
