### ISSUE TITLE
Origin Site Masthead, footer and main nav home links not correct

### ISSUE THREAD

**Issue by usdafsajeff** [usdafsajeff/fsasoftlaunch#4]
On the origin site, the masthead, footer and main nav links for home are directing you back to www.fsa.usda.gov/FSA

![fsa newsroom](https://cloud.githubusercontent.com/assets/11912696/7107509/614c22d8-e135-11e4-837f-04315d5c589b.png)

**Comment by MartinLeborgne** [comment]
Resolved and fixed in Akamai v 183 as well as config changes.  Closed.
