### ISSUE TITLE
DCP Library link goes to a blank page

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#42]
DCP Temporary Directives 
A link called "DCP Temporary Directives" goes to a blank page. The link is on the DCP Library page at: http://www.fsa.usda.gov/programs-and-services/dccp-acre/dcp-lib/index

It may not be a migration issue, but I wanted to note it so we can fix it in the future. 

DCP Temporary Directives
http://www.fsa.usda.gov/FSA/notices?area=home&subject=lare&topic=not&getData=DCCPN

**Comment by MartinLeborgne** [comment]
Hi - This is not a migration issue. But a normal broken link.  Any thoughts on the actual real and correct link? And we can change it?

**Comment by usdafsajeff** [comment]
The query string http://www.fsa.usda.gov/FSA/notices?area=home&subject=lare&topic=not&getData=DCCPN only appears to return "Current" notices not "Obsolete" notices. All of the DCP notices are now "Obsolote" 

I would just remove this link from the page as its not needed any longer. If the business owner wants to add a new link then they can do that when they take over content. For now remove the link. After that close this out.

**Comment by SubbuSarma** [comment]
I have removed the link  from the page.

**Comment by angelamathews** [comment]
Ok. Thanks

Angela
