### ISSUE TITLE
All the links on the Programs and Services page have http://www.apfo.usda.gov in front of them

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#43]
All the links on the Programs and Services at www.fsa.usda.gov list have http://www.apfo.usda.gov in frontn of them. For example: http://www.apfo.usda.gov/programs-and-services/conservation-programs/index

http://www.apfo.usda.gov/programs-and-services/dccp-acre/index

http://www.apfo.usda.gov/programs-and-services/disaster-assistance-program/index

**Comment by rudolfrojas** [comment]
We are not able to recreate this issue, can you please provide us details on what browser your using and how you are getting this? I have tested in I.E. and Firefox and unable to recreate.  Try clearing cache and reloading.

**Comment by angelamathews** [comment]
IE 9, not the compat view... It was a new browser as I just started the computer for the day. APFO was NOT the last section I was looking at. Now after opening a third browser I can see the right links, but it was NOT my imagination.

**Comment by SubbuSarma** [comment]
Issue has been resolved

**Comment by angelamathews** [comment]
Verified links are now forming correctly.
