### ISSUE TITLE
EPAS - AFIDA link going to dev.fsa.usda.gov ....

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#44]
www.fsa.usda.gov in IE 9
On http://www.fsa.usda.gov/programs-and-services/economic-and-policy-analysis/index the following link is incorrect:

The Agricultural Foreign Investment Disclosure Act (AFIDA) is part of NRA http://dev.fsa.usda.gov/FSA/webapp?area=home&subject=ecpa&topic=afa

**Comment by MartinLeborgne** [comment]
Fixed.....please check and verify this, Angela.
Thanks,
Martin

**Comment by usdafsajeff** [comment]
Appears fixed
