### ISSUE TITLE
EPAS: link going to page not found

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#45]
www.fsa.usda.gov in IE 9

In EPAS on :

http://www.fsa.usda.gov/programs-and-services/economic-and-policy-analysis/dairy-and-sweeteners-analysis/index

the following link goes to Page Not Found

News Releases for Sugar, Honey, Dairy, and Livestock Click Here

http://www.fsa.usda.gov/FSA/dsaNewsReleases?area=newsroom&subject=landing&topic=ner&newstype=newsrel

**Comment by MartinLeborgne** [comment]
In progress
Martin will put this filter of dsaNewReleases in Akamai

**Comment by MartinLeborgne** [comment]
ML:  Fixed and implemented w akamai.
Closed.
