### ISSUE TITLE
Farm Bill: PFS link goes to FSA error page

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#46]
www.fsa.usda.gov IE 9

On Farm Bill home page: http://www.fsa.usda.gov/programs-and-services/farm-bill/index

the link below goes to FSA Error page

http://www.fsa.usda.gov/FSA/newsReleases?area=newsroom&subject=landing&newstype=prfactsheet&type=detail&item=pf_20140328_admin_en_cotton.html

Cotton: Fees and Charges Assessed by the Commodity Credit Corporation for Cotton Loans, Loan Forfeitures, and Relocation of Collateral (Mar 28, 2014)

**Comment by SubbuSarma** [comment]
If u go Farm Bill site http://www.fsa.usda.gov/FSA/fbapp?area=fbhome&subject=landing&topic=landing.

and click on Cotton: Fees and Charges Assessed by the Commodity Credit Corporation for Cotton Loans, Loan Forfeitures, and Relocation of Collateral   it is displaying the same  FSA error page.

**Comment by SubbuSarma** [comment]
Right link  has been replaced the broken link.
 http://www.fsa.usda.gov/FSA/newsReleases?area=newsroom&subject=landing&topic=pfs&newstype=prfactsheet&type=detail&item=pf_20140328_admin_en_cotton.html   r

**Comment by angelamathews** [comment]
Verified issue is corrected and link now goes to the Cotton CCC  Fact Sheet
