### ISSUE TITLE
Farm Bill: typo in headline bar on Cotton Transition page

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#47]
www.fsa.usda.gov IE 9

On Cotton Transition page: http://www.fsa.usda.gov/programs-and-services/farm-bill/farm-safety-net/cotton_transition/index

typo in headline bar: Cotton Transistion

**Comment by SubbuSarma** [comment]
I have fixed the typo.

**Comment by angelamathews** [comment]
Verified that typo is corrected now.
