### ISSUE TITLE
Farm Loans: Emergency Loans- farm loan appl forms link going to wrong page

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#49]
www.fsa.usda.gov  IE 9
On the Emergency Farm Loans page at: http://www.fsa.usda.gov/programs-and-services/farm-loan-programs/emergency-farm-loans/index

The "Find Farm Loan Application Forms"  link (http://www.fsa.usda.gov/FSA/webapp?area=home&subject=fmlp&topic=fla ) goes back to Farm Loan home page; I think it is probably supposed to to the Farm Loan App Forms web page.

**Comment by MartinLeborgne** [comment]
Yeah- Akamai redirect so can you tell me the link where it needs to go to?

Thanks,
Martin Leborgne

**Comment by angelamathews** [comment]
http://www.fsa.usda.gov/programs-and-services/farm-loan-programs/farm-loan-application-forms/index is the farm loan app forms page. I have found several links on different pages that go back to the Farm Loan home page instead of a specific Farm Loan sub-category page. How do you want me to list them or what do you want to do about them?

Thanks
Angela

**Comment by MartinLeborgne** [comment]
Angela - This has been fixed.  For a double check can you verify that it indeed has been fixed?

**Comment by MartinLeborgne** [comment]
Verified and closing
