### ISSUE TITLE
eFOIA Request Form not working

### ISSUE THREAD

**Issue by usdafsajeff** [usdafsajeff/fsasoftlaunch#5]
When you select the submit button on the eFOIA request form http://www.fsa.usda.gov/FSA/eFOIARequest?area=newsroom&subject=landing&topic=efoia a page not found error is displayed.

**Comment by angelamathews** [comment]
NO alt text on photos on FSA Admin Bio page: http://www.fsa.usda.gov/about-fsa/fsa-biographies/index

**Comment by usdafsajeff** [comment]
Resolved
