### ISSUE TITLE
Laws and Regs:Related Topic  'Handbook' does not go to handbooks

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#50]
On the page: http://www.fsa.usda.gov/programs-and-services/laws-and-regulations/index

In the Related Topics list, the Handbooks link does not take you to the handbook section. It just opens a new LR page that looks like the L&R home page 

Also
The link: Click here to access the entire list of Handbooks 
goes back to the L&R home page too. It doesn't go to a Handbook list. Is this still an Akamai thing? I don't know where the Handbook list is unless it is on the Handbook home page that I can't get to right now.

**Comment by angelamathews** [comment]
Disregard, I can see it now.  All i did was move to a new page in L&R... don't understand that.

**Comment by SubbuSarma** [comment]
I have fixed and it is going to handbooks.

**Comment by angelamathews** [comment]
Verified that Related Topic is going to handbooks page.
