### ISSUE TITLE
Outreach: Resources - tobacco buy out program going to http://www.fsa.usda.gov/tobacco

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#51]
IE 9

The last link on Outreach Resources - (http://www.fsa.usda.gov/programs-and-services/outreach-and-education/resources/index goes back to http://www.fsa.usda.gov/tobacco and is "page not found"

I think the only tobacco page we have on the new site is: http://www.fsa.usda.gov/programs-and-services/economic-and-policy-analysis/fibers-peanuts-tobacco/tobacco-assessment-reports/index 

I don't know if this is the appropriate page or not. May need to check with Jeff or Latrice Hill in Outreach at some point.

**Comment by SubbuSarma** [comment]
I have fixed the url. 

http://www.fsa.usda.gov/FSA/newsReleases?area=newsroom&subject=landing&topic=pfs&newstype=prfactsheet&type=detail&item=pf_20091008_insup_en_ttpp09.html

**Comment by angelamathews** [comment]
Verified. Tobacco link is corrected and is  now going to Tobacco Buyout Program fact sheet.
