### ISSUE TITLE
Contact Us page: link to APFO goes back to old site and is blank

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#52]
IE 9

On the Contact Us page at the very bottom of the page at: http://www.fsa.usda.gov/contact-us the 'Visit the APFO' link goes back to an empty page on the old site. Current link is: http://www.fsa.usda.gov/FSA/apfoapp

**Comment by sonjaeasley** [comment]
This link has been fixed. Please let me know if you have any questions.

**Comment by MartinLeborgne** [comment]
JML: Verified and closed
