### ISSUE TITLE
Contact Us page: AskFSA link at top of page goes to Answers tab instead of Home tab

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#53]
IE 9 

On the Contact Us page at: http://www.fsa.usda.gov/contact-us the AskFSA link at the top of the page needs to be directed to the AskFSA Home page at: http://askfsa.custhelp.com/ right now it is: http://askfsa.custhelp.com/app/answers/list . Minor issue I guess, but needs to be fixed at some point.

**Comment by sonjaeasley** [comment]
The AskFSA link at the top of the Contact Us page now goes to the AskFSA Home page.

**Comment by angelamathews** [comment]
Verified that AskFSA link goes back to home for AskFSA. Thanks
