### ISSUE TITLE
Site Map: Bad conservation links; the URL is slightly different than the working pages

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#55]
On the SiteMap: at: http://www.fsa.usda.gov/help/site-map I am getting a page not found on these Conservation links. They look like they have a  "-program" at the end of links that don't work ;The good links don't include that. 

bad link: http://www.fsa.usda.gov/programs-and-services/conservation-programs/emergency-conservation-program/index

Good link: http://www.fsa.usda.gov/programs-and-services/conservation-programs/emergency-conservation/index  missing "-program"

Bad link: http://www.fsa.usda.gov/programs-and-services/conservation-programs/conservation-reserve-enhancement-program/index 

Good link: http://www.fsa.usda.gov/programs-and-services/conservation-programs/conservation-reserve-enhancement/index     Missing" -program" in URL

These are also bad links: 
http://www.fsa.usda.gov/programs-and-services/conservation-programs/grassland-reserve-program/index

http://www.fsa.usda.gov/programs-and-services/conservation-programs/farmable-wetlands-program/index

http://www.fsa.usda.gov/programs-and-services/conservation-programs/source-water-protection-program/index

**Comment by psleman** [comment]
The links have been fixed and published.

**Comment by angelamathews** [comment]
Verified that links under Conservation section on Site Map now go to the correct pages. Thanks

**Comment by MartinLeborgne** [comment]
Verified and closed
