### ISSUE TITLE
Site Map: Disaster Assistance Tool link goes to Contact Us page

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#56]
On the Site Map at : http://www.fsa.usda.gov/help/site-map , the Disaster Assistance Tool link goes to the Contact Us page. 

It says Disaster Asstance Elig Tool, but the URL is http://www.fsa.usda.gov/contact-us .

**Comment by angelamathews** [comment]
Verified that this page no longer goes to Contact Us page but to the Disaster Home page. Thanks

**Comment by MartinLeborgne** [comment]
Thank you, All...Closing
