### ISSUE TITLE
YouTube Script on Home Page

### ISSUE THREAD

**Issue by usdafsajeff** [usdafsajeff/fsasoftlaunch#59]
The script on the Home Page for the YouTube feed is broke.

![home_youtube](https://cloud.githubusercontent.com/assets/11912696/7321455/36624a22-ea70-11e4-9bca-40017c45a988.png)

**Comment by NavyaVullanki** [comment]
This is Fixed. The fix is shown in origin2.  Will take some time to show the change in www.
