### ISSUE TITLE
Origin2 is down.

### ISSUE THREAD

**Issue by Asimea** [usdafsajeff/fsasoftlaunch#61]
The development server-Origin2 has been down since early this morning.

**Comment by SubbuSarma** [comment]
I have notified Vivek about origin2 and he is looking into the issue.

**Comment by NavyaVullanki** [comment]
It is up now. Please test.

**Comment by SubbuSarma** [comment]
it is up and i have tested it.

**Comment by NavyaVullanki** [comment]
Now the the site is up and running. Vivek said that they had a Linux patch yesterday night but they have placed the scripts for the site to be up and running. So he is trouble shooting the issue with Linux team to check why it went down inspite of having the scripts in place.

**Comment by Asimea** [comment]
The server is up and running.  Thanks all.

**Comment by Asimea** [comment]
The server is up and running. Thanks all.

**Comment by rudolfrojas** [comment]
Looking fine to me as well.at home.
